name: WAGEncryption
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  cipher:
    git: git://github.com/SecareLupus/cipher.git
  rsa_pkcs:
    git: https://github.com/SecareLupus/rsa_pkcs.git
  dev_random: "^0.0.4"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
